Add check_special_characters decorator and add precommit
matheuscas/pycpfcnpj pull request #40
Opened 2022-04-29 23:44 UTC by jeffersonkr

Nesse PR estou realizando as issues #32  e #39

2022-05-12 23:13 UTC, matheuscas commented
Vc pode dividir os PR, por favor? Um PR por issue. Valeu. :)

2022-06-04 23:47 UTC, matheuscas requested changes
Boa ideia do decorator! 👏🏼 
Deixei apenas um comentário e faltou o teste do decorator ;) .

2022-06-04 23:47 UTC, matheuscas commented on pycpfcnpj/compatible.py
> +        not_digit = list(filter(lambda x: not x.isdigit(), clear_punctuation(document)))
Use `list compreensions` em vez de `list(filter`. Torna o código mais legível.

2022-06-06 16:59 UTC, jeffersonkr commented
os testes ja foram inclusos, pode ver que temos ´invalid_cpf_with_special_character´ e outros casos special characters no caso ela retorna false demonstrando que o decorator está funcionando corretamente

2022-07-10 18:22 UTC, merged